services:
  neo4j:
    image: neo4j:5.20-community      # ou neo4j:5.20 + linha de licença
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test12345   # ≥ 8 caracteres
      # - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes   # só se usar Enterprise
      - NEO4J_PLUGINS=["apoc"]
